import { NextRequest, NextResponse } from 'next/server';
import { generateContentWithFallback, insightResponseSchema } from '@/lib/gemini-server';

export const dynamic = 'force-dynamic';

const INSIGHTS_SYSTEM_INSTRUCTION = `You are the Personal Introspective Analyst & Longitudinal Growth Synthesizer.
Your responsibility is to analyze a collection of historical journal entries written by a single person over time.
Your analysis must be compassionate, psychologically sound, intellectually rigorous, and empowering.

GOALS:
1. Synthesize recurring themes and subconscious threads across their recent reflections.
2. Characterize the emotional trajectory (e.g., resilience building, moving through creative blocks, relational healing).
3. Offer 2-3 deep, constructive reflective questions or mindful invitations that inspire the user's next journaling session.
4. Conform strictly to the requested JSON schema.`;

export async function POST(req: NextRequest) {
  try {
    let body: Record<string, unknown>;
    try {
      body = (await req.json()) || {};
    } catch {
      return NextResponse.json({ error: 'Invalid JSON payload' }, { status: 400 });
    }

    const entries = Array.isArray(body.journalSummaries) ? body.journalSummaries : [];
    if (entries.length === 0) {
      return NextResponse.json({ error: 'At least one journal entry is needed to generate insights' }, { status: 400 });
    }

    // Limit to latest 15 entries for concise, rich analysis
    const scopedEntries = entries.slice(0, 15);

    const summariesContext = scopedEntries
      .map((entry: { title?: string; summary?: string; mood?: string; keyThemes?: string[]; createdAt?: string }, idx: number) => {
        const title = entry.title || `Entry #${idx + 1}`;
        const mood = entry.mood || 'Unspecified';
        const themes = Array.isArray(entry.keyThemes) ? entry.keyThemes.join(', ') : '';
        const summary = typeof entry.summary === 'string' ? entry.summary.slice(0, 1500) : '';
        const date = entry.createdAt ? new Date(entry.createdAt).toLocaleDateString() : '';
        return `[ENTRY ${idx + 1} - ${date} | Title: "${title}" | Mood: ${mood} | Themes: ${themes}]\nSummary: ${summary}`;
      })
      .join('\n\n---\n\n');

    const contents = [
      {
        role: 'user',
        parts: [
          {
            text: `<user_journal_content>\nHISTORICAL JOURNAL ENTRIES DATASET:\n${summariesContext}\n</user_journal_content>\n\nPlease synthesize an longitudinal emotional and thematic reflection report according to the schema.`,
          },
        ],
      },
    ];

    const { text, modelUsed } = await generateContentWithFallback({
      systemInstruction: INSIGHTS_SYSTEM_INSTRUCTION,
      contents,
      responseSchema: insightResponseSchema,
      responseMimeType: 'application/json',
      temperature: 0.4,
    });

    let structuredData;
    try {
      structuredData = JSON.parse(text);
    } catch (parseError) {
      console.error('Failed to parse Gemini insights JSON:', parseError, 'Raw text:', text);
      return NextResponse.json({ error: 'Invalid structured output generated by model' }, { status: 502 });
    }

    return NextResponse.json({
      ...structuredData,
      modelUsed,
      entryCountAnalyzed: scopedEntries.length,
      generatedAt: new Date().toISOString(),
    });
  } catch (err: unknown) {
    console.error('Error in /api/gemini/insights:', err);
    const errorMessage = err instanceof Error ? err.message : 'Insights synthesis error';
    return NextResponse.json(
      { error: 'Failed to generate personal reflection insights. Please try again.', details: process.env.NODE_ENV === 'development' ? errorMessage : undefined },
      { status: 500 }
    );
  }
}
