import { NextRequest, NextResponse } from 'next/server';
import { generateContentWithFallback, summaryResponseSchema } from '@/lib/gemini-server';

export const dynamic = 'force-dynamic';

const SUMMARY_SYSTEM_INSTRUCTION = `You are the Journal Summarization & Reflection Architect.
Your task is to analyze a completed multi-turn personal journal conversation and distill it into an enduring, beautifully crafted personal journal record.

CRITICAL DIRECTIVES:
1. Objectively extract the core intellectual, emotional, and pragmatic substance of the session.
2. Formulate an evocative, elegant title (max 6 words).
3. Draft a thoughtful narrative summary (2-4 paragraphs) that honors the user's authentic voice.
4. Accurately identify the predominant mood and numeric sentiment valence (-1.0 to 1.0).
5. Extract key themes (3 to 5 tags).
6. Isolate any commitments, micro-habits, or action items discussed.
7. Return strictly valid JSON conforming to the requested schema.`;

export async function POST(req: NextRequest) {
  try {
    let body: Record<string, unknown>;
    try {
      body = (await req.json()) || {};
    } catch {
      return NextResponse.json({ error: 'Invalid JSON payload' }, { status: 400 });
    }

    const rawMessages = Array.isArray(body.messages) ? body.messages : [];
    if (rawMessages.length === 0) {
      return NextResponse.json({ error: 'At least one message is required to generate a summary' }, { status: 400 });
    }

    // Format conversation transcript with boundary isolation
    const transcript = rawMessages
      .map((m: { role?: string; content?: string }) => {
        const speaker = m.role === 'assistant' ? 'Journal Companion' : 'User';
        const cleanContent = typeof m.content === 'string' ? m.content.slice(0, 3000) : '';
        return `[${speaker}]: ${cleanContent}`;
      })
      .join('\n\n');

    const contents = [
      {
        role: 'user',
        parts: [
          {
            text: `<user_journal_content>\nTRANSCRIPT OF JOURNALING SESSION:\n${transcript}\n</user_journal_content>\n\nPlease synthesize this personal journaling session into a structured reflection record according to the required schema.`,
          },
        ],
      },
    ];

    // Validate server environment API key
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey || apiKey.trim() === '') {
      return NextResponse.json(
        { error: 'GEMINI_API_KEY is not configured in environment variables.' },
        { status: 401 }
      );
    }

    const { text, modelUsed } = await generateContentWithFallback({
      systemInstruction: SUMMARY_SYSTEM_INSTRUCTION,
      contents,
      responseSchema: summaryResponseSchema,
      responseMimeType: 'application/json',
      temperature: 0.3, // Lower temperature for consistent, analytical structured extraction
    });

    let structuredData;
    try {
      structuredData = JSON.parse(text);
    } catch (parseError) {
      console.error('Failed to parse Gemini summary JSON:', parseError, 'Raw text:', text);
      return NextResponse.json({ error: 'Invalid structured output generated by model' }, { status: 502 });
    }

    return NextResponse.json({
      ...structuredData,
      modelUsed,
      generatedAt: new Date().toISOString(),
    });
  } catch (err: unknown) {
    console.error('Error in /api/gemini/summarize:', err);
    const errorMessage = err instanceof Error ? err.message : 'Summarization error';
    return NextResponse.json(
      { error: 'Failed to synthesize journal summary. Please try again.', details: process.env.NODE_ENV === 'development' ? errorMessage : undefined },
      { status: 500 }
    );
  }
}
